spring:
    profiles:
        active: dev

---

spring:
    profiles: dev
    main:
        show_banner: false
    thymeleaf:
        cache: false
telegramserver:
    hostname: localhost
    port: 2342


